### ISSUE TITLE
Seeing the Code like <Playground>

### ISSUE THREAD

**Issue by ghost** [zicodeng/docz-iframe-playground#1]
First off, this solved my styling issues 100000% so thank you!

My only critique is not being able to see the Code when using this. But if I wrap it in `<Playground>` I then see the `IframePlayground` inside of my code.

**Comment by zicodeng** [comment]
Hi, I am glad it solved your issues. Regarding your critique, I recommend you to check out another Docz theme I built: https://github.com/zicodeng/docz-theme-ztopia, it has build-in iframe support and should solve this issue
